/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsSlugRouteImport } from './routes/quests.$slug'
import { Route as BuildingSlugRouteImport } from './routes/building.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsSlugRoute = QuestsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => QuestsRoute,
} as any)
const BuildingSlugRoute = BuildingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuildingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRouteWithChildren
  '/contact': typeof ContactRoute
  '/quests': typeof QuestsRouteWithChildren
  '/work': typeof WorkRoute
  '/building/$slug': typeof BuildingSlugRoute
  '/quests/$slug': typeof QuestsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRouteWithChildren
  '/contact': typeof ContactRoute
  '/quests': typeof QuestsRouteWithChildren
  '/work': typeof WorkRoute
  '/building/$slug': typeof BuildingSlugRoute
  '/quests/$slug': typeof QuestsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building': typeof BuildingRouteWithChildren
  '/contact': typeof ContactRoute
  '/quests': typeof QuestsRouteWithChildren
  '/work': typeof WorkRoute
  '/building/$slug': typeof BuildingSlugRoute
  '/quests/$slug': typeof QuestsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/building'
    | '/contact'
    | '/quests'
    | '/work'
    | '/building/$slug'
    | '/quests/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/building'
    | '/contact'
    | '/quests'
    | '/work'
    | '/building/$slug'
    | '/quests/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/building'
    | '/contact'
    | '/quests'
    | '/work'
    | '/building/$slug'
    | '/quests/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildingRoute: typeof BuildingRouteWithChildren
  ContactRoute: typeof ContactRoute
  QuestsRoute: typeof QuestsRouteWithChildren
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$slug': {
      id: '/quests/$slug'
      path: '/$slug'
      fullPath: '/quests/$slug'
      preLoaderRoute: typeof QuestsSlugRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/building/$slug': {
      id: '/building/$slug'
      path: '/$slug'
      fullPath: '/building/$slug'
      preLoaderRoute: typeof BuildingSlugRouteImport
      parentRoute: typeof BuildingRoute
    }
  }
}

interface BuildingRouteChildren {
  BuildingSlugRoute: typeof BuildingSlugRoute
}

const BuildingRouteChildren: BuildingRouteChildren = {
  BuildingSlugRoute: BuildingSlugRoute,
}

const BuildingRouteWithChildren = BuildingRoute._addFileChildren(
  BuildingRouteChildren,
)

interface QuestsRouteChildren {
  QuestsSlugRoute: typeof QuestsSlugRoute
}

const QuestsRouteChildren: QuestsRouteChildren = {
  QuestsSlugRoute: QuestsSlugRoute,
}

const QuestsRouteWithChildren =
  QuestsRoute._addFileChildren(QuestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildingRoute: BuildingRouteWithChildren,
  ContactRoute: ContactRoute,
  QuestsRoute: QuestsRouteWithChildren,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
